language: go
go:
- 1.12.x
- 1.13.x
os:
  - linux
  - osx
sudo: false
stage: deploy
go_import_path: github.com/cespare/reflex
before_deploy:
- env GO111MODULE=on go mod download
- "./script/build-all.bash"
deploy:
  provider: releases
  api_key:
    secure: oEHfGPsuBH4nfWiOdGwVcZfoSjUzfYRi+F2EHaDiKBichiT90lVoyb/1X+iaUh2MUpyTnEOWscfbjxdlgLiMnoRqZUlf6ISk06TWGiNmn306JpKC9IzFIUFwpWo74aT08K6DLveklrt8MX5KDGsVdqpj+p6hsmldlaH5aBvzookwxLsVSiTvilDQwk208bQt6EyVvvJhNWg2vUnzZ6aBGQTAOIM9XIvtXIhFJTcxMNUTSaPVOnfmZla/i6g85cedfRIdHqNaBeI8e8MVSP4Hg01mog2Msq6dqbMViAbVAzt8t2ejXW1MRwx7UQ/rQC+RjbT0MX49kQ+nhEzhudAtjk47PGmPm+QPldwKmuucswp+RZVMNPqZ2ZfSnpqh10N0TMtd3FDJ3nu4kEfICGqzD6PuoWghnAe2YYIiaqBBH6Q326ci9is6WUYNABSdh1svz/dKU76oAme+JYTawVxmQW4ldJGWdu7HNjme5SD1K/s/XmH7IDNUuoqG2wKMUApxPq05xGquWjz0A7vcQMbUbHHoTqGXvQmjciyNpghdCbwr8VYycDMSygMxaWMTWwyImwyEOUy7E1qKBBA0VSjdREAhfDN4GlRUmv9+iu4s2E/HfwUGmtrhaKyboWpZRkpWrGoXJwqADlpGGSzSBaMqznzT+3BsotzMSIfxWoWBDjg=
  file:
    - release/reflex-darwin-386
    - release/reflex-darwin-386.sha256
    - release/reflex-darwin-amd64
    - release/reflex-darwin-amd64.sha256
    - release/reflex-freebsd-386
    - release/reflex-freebsd-386.sha256
    - release/reflex-freebsd-amd64
    - release/reflex-freebsd-amd64.sha256
    - release/reflex-linux-386
    - release/reflex-linux-386.sha256
    - release/reflex-linux-amd64
    - release/reflex-linux-amd64.sha256
    - release/reflex-linux-arm
    - release/reflex-linux-arm.sha256
    - release/reflex-linux-arm64
    - release/reflex-linux-arm64.sha256
    - release/reflex-linux-ppc64
    - release/reflex-linux-ppc64.sha256
    - release/reflex-linux-ppc64le
    - release/reflex-linux-ppc64le.sha256
    - release/reflex-linux-s390x
    - release/reflex-linux-s390x.sha256
  skip_cleanup: true
  on:
    branch: master
    tags: true
